### ISSUE TITLE
ADB issue

### ISSUE THREAD

**Issue by naixx** [rpuxa/SuperWirelessAdb#2]
While plugin is enabled no other adb instances can be launched
```
$ adb tcpip 5555
adb server is out of date.  killing...
ADB server didn't ACK
* failed to start daemon *
error:
```

Overall, connection doesn't work with device

**Comment by rpuxa** [comment]
While plugin is enabling or disabling it doesn't execute any adb commands. 
The only thing that it execute, this is
**adb connect <ip_address>** - while you connecting adb,
**adb disconnect <ip_address>** - while you disconnecting adb,
and in rare case, when you get 10061 adb error, plugin try fix with this commands sequence:
**adb usb**
**adb kill-server**
**adb tcpip 5555**
**adb connect <ip_address>**
but it will ask you to connect USB cable

[Adb class source](https://github.com/rpuxa/SuperWirelessAdb/blob/master/desktop/src/main/java/ru/rpuxa/desktop/wireless/Adb.kt)
