### ISSUE TITLE
The logcat show OFFLINE when the toast show connected

### ISSUE THREAD

**Issue by Momohanfeng** [rpuxa/SuperWirelessAdb#3]
The Logcat show 192.168.xx.xx:5555[OFFLINE] when the device switch is ON, and the toast of studio is showing the device is connected.

**Comment by rpuxa** [comment]
It could be due bad connection (message about disconnect adb was lost). I will try to fix it in next version

**Comment by afilp** [comment]
I get "error, please try again", but shows that it found it, although "offline"

`192.168.0.21:5555       offline`

So, because it is offline, I cannot use adb. What should I do?

**Comment by rpuxa** [comment]
As I already said, messages between PC and phone may be lost due bad connection. I am trying to fix it now

**Comment by afilp** [comment]
Thanks!

**Comment by Momohanfeng** [comment]
If I met this issue, I type the command below to resolve it successfully.
`adb kill-server`
`adb tcpip 5555`
`adb connect 192.168.x.x`

the 2nd command will show restarting in TCP mode port:5555. and if you still cannot connect, please try these command again. I try it every five successful four times.
